# Basic neural network using numpy list 

In [2]:
import tensorflow as tf
import numpy as np
from keras import layers, Sequential

In [34]:
l0 = layers.Dense(units=2, input_shape=[1])
l1 = layers.Dense(units=1)
model = Sequential([l0, l1])
model.compile(optimizer='sgd', loss='mean_squared_error')

In [32]:
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

In [33]:
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - loss: 9.4642
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 6.1689
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 3.9154
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 2.4781
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1.6437
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.1959
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.9615
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.8311
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.7474
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.6846
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.6317
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.5844
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.5411
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.5010
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.4637
Epoch 16/500
1/1 ━

In [29]:
model.predict(np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([[18.999992]], dtype=float32)

In [35]:
model.get_weights()

[array([[-0.9821429, -1.3918393]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.7868556],
        [0.8752166]], dtype=float32),
 array([0.], dtype=float32)]

In [36]:
l0.get_weights()

[array([[-0.9821429, -1.3918393]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [37]:
l1.get_weights()

[array([[0.7868556],
        [0.8752166]], dtype=float32),
 array([0.], dtype=float32)]